create table fin.dimdate
(
    "DateKey"           integer,
    "Date"              timestamp(3),
    "FullDateUK"        char(10),
    "FullDateUSA"       char(10),
    "DayOfMonth"        varchar(2),
    "DaySuffix"         varchar(4),
    "DayName"           varchar(9),
    "DayOfWeekUSA"      char,
    "DayOfWeekUK"       char,
    "DayOfWeekInMonth"  varchar(2),
    "DayOfWeekInYear"   varchar(2),
    "DayOfQuarter"      varchar(3),
    "DayOfYear"         varchar(3),
    "WeekKey"           integer,
    "WeekOfMonth"       varchar(1),
    "WeekOfQuarter"     varchar(2),
    "WeekOfYear"        varchar(2),
    "MonthKey"          integer,
    "Month"             varchar(2),
    "MonthName"         varchar(9),
    "MonthOfQuarter"    varchar(2),
    "QuarterKey"        integer,
    "Quarter"           char,
    "QuarterName"       varchar(9),
    "Year"              char(4),
    "YearName"          char(7),
    "MonthYear"         char(10),
    "MMYYYY"            char(6),
    "FirstDayOfMonth"   date,
    "LastDayOfMonth"    date,
    "FirstDayOfQuarter" date,
    "LastDayOfQuarter"  date,
    "FirstDayOfYear"    date,
    "LastDayOfYear"     date,
    "IsHolidayUSA"      boolean,
    "IsWeekday"         boolean,
    "HolidayUSA"        varchar(50),
    "IsHolidayUK"       boolean,
    "HolidayUK"         varchar(50)
);

alter table fin.dimdate
    owner to postgres;

