create table fin.symbolprofilemarketwatch
(
    "SymbolProfileMarketWatchID"       integer,
    "Symbol"                           varchar(50),
    "CompanyName"                      varchar(100),
    "CompanyDescription"               char(3999),
    "PECurrent"                        numeric(22, 2),
    "PERatioWithExtraordinaryItems"    numeric(22, 2),
    "PERatioWithoutExtraordinaryItems" numeric(22, 2),
    "PriceToSalesRatio"                numeric(22, 2),
    "PriceToBookRatio"                 numeric(22, 2),
    "PriceToCashFlowRatio"             numeric(22, 2),
    "EnterpriseValueToEBITDA"          numeric(22, 2),
    "EnterpriseValueToSales"           numeric(22, 2),
    "TotalDebtToEnterpriseValue"       numeric(22, 2),
    "RevenuePerEmployee"               numeric(22, 2),
    "IncomePerEmployee"                numeric(22, 2),
    "ReceivablesTurnover"              numeric(22, 2),
    "TotalAssetTurnover"               numeric(22, 2),
    "CurrentRatio"                     numeric(22, 2),
    "QuickRatio"                       numeric(22, 2),
    "CashRatio"                        numeric(22, 2),
    "GrossMargin"                      numeric(22, 2),
    "OperatingMargin"                  numeric(22, 2),
    "PretaxMargin"                     numeric(22, 2),
    "NetMargin"                        numeric(22, 2),
    "ReturnOnAssets"                   numeric(22, 2),
    "ReturnOnEquity"                   numeric(22, 2),
    "ReturnOnTotalCapital"             numeric(22, 2),
    "ReturnOnInvestedCapital"          numeric(22, 2),
    "TotalDebtToTotalEquity"           numeric(22, 2),
    "TotalDebtToTotalCapital"          numeric(22, 2),
    "TotalDebtToTotalAssets"           numeric(22, 2),
    "LongTermDebtToEquity"             numeric(22, 2),
    "LongTermDebtToTotalCapital"       numeric(22, 2),
    "Industry"                         varchar(50),
    "Sector"                           varchar(50),
    "FiscalYearEnd"                    varchar(50),
    "Revenue"                          numeric(22, 2),
    "NetIncome"                        numeric(22, 2),
    "LastYearSalesGrowth"              numeric(22, 4),
    "Employees"                        integer,
    "ProfileURL"                       varchar(300),
    "ImportTime"                       timestamp(3)
);

alter table fin.symbolprofilemarketwatch
    owner to postgres;

