create table fin.symbolprofilefinviz
(
    "SymbolProfileFinvizID" integer,
    "Symbol"                varchar(50),
    "Company"               varchar(100),
    "Sector"                varchar(50),
    "Industry"              varchar(50),
    "Country"               varchar(50),
    "Market_Cap"            varchar(50),
    "P/E"                   numeric(22, 2),
    "Fwd_P/E"               numeric(22, 2),
    "PEG"                   numeric(22, 2),
    "P/S"                   numeric(22, 2),
    "P/B"                   numeric(22, 2),
    "P/C"                   numeric(22, 2),
    "P/FCF"                 numeric(22, 2),
    "Dividend"              numeric(22, 4),
    "Payout_Ratio"          numeric(22, 4),
    "EPS"                   numeric(22, 2),
    "EPS_this_Y"            numeric(22, 4),
    "EPS_next_Y"            numeric(22, 4),
    "EPS_past_5Y"           numeric(22, 4),
    "EPS_next_5Y"           numeric(22, 4),
    "Sales_past_5Y"         numeric(22, 4),
    "EPS_Q/Q"               numeric(22, 4),
    "Sales_Q/Q"             numeric(22, 4),
    "Outstanding"           varchar(50),
    "Float"                 varchar(50),
    "Insider_Own"           numeric(22, 4),
    "Insider_Trans"         numeric(22, 4),
    "Inst_Own"              numeric(22, 4),
    "Inst_Trans"            numeric(22, 4),
    "Float_Short"           numeric(22, 4),
    "Short_Ratio"           numeric(22, 2),
    "ROA"                   numeric(22, 4),
    "ROE"                   numeric(22, 4),
    "ROI"                   numeric(22, 4),
    "Curr_R"                numeric(22, 2),
    "Quick_R"               numeric(22, 2),
    "LTDebt/Eq"             numeric(22, 2),
    "Debt/Eq"               numeric(22, 2),
    "Gross_M"               numeric(22, 4),
    "Oper_M"                numeric(22, 4),
    "Profit_M"              numeric(22, 4),
    "Perf_Week"             numeric(22, 4),
    "Perf_Month"            numeric(22, 4),
    "Perf_Quart"            numeric(22, 4),
    "Perf_Half"             numeric(22, 4),
    "Perf_Year"             numeric(22, 4),
    "Perf_YTD"              numeric(22, 4),
    "Beta"                  numeric(22, 2),
    "ATR"                   numeric(22, 2),
    "Volatility_W"          numeric(22, 4),
    "Volatility_M"          numeric(22, 4),
    "SMA20"                 numeric(22, 4),
    "SMA50"                 numeric(22, 4),
    "SMA200"                numeric(22, 4),
    "50D_High"              numeric(22, 4),
    "50D_Low"               numeric(22, 4),
    "52W_High"              numeric(22, 4),
    "52W_Low"               numeric(22, 4),
    "RSI"                   numeric(22, 2),
    "from_Open"             numeric(22, 4),
    "Gap"                   numeric(22, 4),
    "Recom"                 numeric(22, 2),
    "Avg_Volume"            varchar(50),
    "Rel_Volume"            numeric(22, 2),
    "Price"                 numeric(22, 2),
    "Change"                numeric(22, 4),
    "Volume"                bigint,
    "Earnings"              varchar(50),
    "Target_Price"          numeric(22, 2),
    "IPO_Date"              timestamp(3),
    "ImportTime"            timestamp(3)
);

alter table fin.symbolprofilefinviz
    owner to postgres;

