create table fin.symbol_profile_market_watch
(
    symbol_profile_market_watch_id       integer,
    symbol                               varchar(50),
    company_name                         varchar(100),
    company_description                  char(3999),
    pe_current                           numeric(22, 2),
    pe_ratio_with_extraordinary_items    numeric(22, 2),
    pe_ratio_without_extraordinary_items numeric(22, 2),
    price_to_sales_ratio                 numeric(22, 2),
    price_to_book_ratio                  numeric(22, 2),
    price_to_cash_flow_ratio             numeric(22, 2),
    enterprise_value_to_ebitda           numeric(22, 2),
    enterprise_value_to_sales            numeric(22, 2),
    total_debt_to_enterprise_value       numeric(22, 2),
    revenue_per_employee                 numeric(22, 2),
    income_per_employee                  numeric(22, 2),
    receivables_turnover                 numeric(22, 2),
    total_asset_turnover                 numeric(22, 2),
    current_ratio                        numeric(22, 2),
    quick_ratio                          numeric(22, 2),
    cash_ratio                           numeric(22, 2),
    gross_margin                         numeric(22, 2),
    operating_margin                     numeric(22, 2),
    pretax_margin                        numeric(22, 2),
    net_margin                           numeric(22, 2),
    return_on_assets                     numeric(22, 2),
    return_on_equity                     numeric(22, 2),
    return_on_total_capital              numeric(22, 2),
    return_on_invested_capital           numeric(22, 2),
    total_debt_to_total_equity           numeric(22, 2),
    total_debt_to_total_capital          numeric(22, 2),
    total_debt_to_total_assets           numeric(22, 2),
    long_term_debt_to_equity             numeric(22, 2),
    long_term_debt_to_total_capital      numeric(22, 2),
    industry                             varchar(50),
    sector                               varchar(50),
    fiscal_year_end                      varchar(50),
    revenue                              numeric(22, 2),
    net_income                           numeric(22, 2),
    last_year_sales_growth               numeric(22, 4),
    employees                            integer,
    profile_url                          varchar(300),
    import_time                          timestamp(3)
);

alter table fin.symbol_profile_market_watch
    owner to postgres;

