create table fin.symbol_profile_finviz
(
    symbol_profile_finviz_id integer,
    symbol                   varchar(50),
    company                  varchar(100),
    sector                   varchar(50),
    industry                 varchar(50),
    country                  varchar(50),
    market_cap               varchar(50),
    p_e                      numeric(22, 2),
    fwd_p_e                  numeric(22, 2),
    peg                      numeric(22, 2),
    p_s                      numeric(22, 2),
    p_b                      numeric(22, 2),
    p_c                      numeric(22, 2),
    p_fcf                    numeric(22, 2),
    dividend                 numeric(22, 4),
    payout_ratio             numeric(22, 4),
    eps                      numeric(22, 2),
    eps_this_y               numeric(22, 4),
    eps_next_y               numeric(22, 4),
    eps_past_5y              numeric(22, 4),
    eps_next_5y              numeric(22, 4),
    sales_past_5y            numeric(22, 4),
    eps_q_q                  numeric(22, 4),
    sales_q_q                numeric(22, 4),
    outstanding              varchar(50),
    float                    varchar(50),
    insider_own              numeric(22, 4),
    insider_trans            numeric(22, 4),
    inst_own                 numeric(22, 4),
    inst_trans               numeric(22, 4),
    float_short              numeric(22, 4),
    short_ratio              numeric(22, 2),
    roa                      numeric(22, 4),
    roe                      numeric(22, 4),
    roi                      numeric(22, 4),
    curr_r                   numeric(22, 2),
    quick_r                  numeric(22, 2),
    lt_debt_eq               numeric(22, 2),
    debt_eq                  numeric(22, 2),
    gross_m                  numeric(22, 4),
    oper_m                   numeric(22, 4),
    profit_m                 numeric(22, 4),
    perf_week                numeric(22, 4),
    perf_month               numeric(22, 4),
    perf_quart               numeric(22, 4),
    perf_half                numeric(22, 4),
    perf_year                numeric(22, 4),
    perf_ytd                 numeric(22, 4),
    beta                     numeric(22, 2),
    atr                      numeric(22, 2),
    volatility_w             numeric(22, 4),
    volatility_m             numeric(22, 4),
    sma20                    numeric(22, 4),
    sma50                    numeric(22, 4),
    sma200                   numeric(22, 4),
    "50d_high"               numeric(22, 4),
    "50d_low"                numeric(22, 4),
    "52w_high"               numeric(22, 4),
    "52w_low"                numeric(22, 4),
    rsi                      numeric(22, 2),
    from_open                numeric(22, 4),
    gap                      numeric(22, 4),
    recom                    numeric(22, 2),
    avg_volume               varchar(50),
    rel_volume               numeric(22, 2),
    price                    numeric(22, 2),
    change                   numeric(22, 4),
    volume                   bigint,
    earnings                 varchar(50),
    target_price             numeric(22, 2),
    ipo_date                 timestamp(3),
    importtime               timestamp(3)
);

alter table fin.symbol_profile_finviz
    owner to postgres;

